organisation: "pyecharts"
author: "pyecharts dev team"
contact: "info@pyecharts.com"
company: "pyecharts dev team"
gitignore_global_rulesets:
  - Emacs
  - macOS
  - Windows
keywords:
  - pyecharts
  - chart
